# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y68cnfYqx9yUdv2BRM0qPw4FgVC26QZz
"""

import pandas as pd
import numpy as np
import datetime
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import calendar

data=pd.read_csv("/My Uber Drives - 2016.csv")

data.head()

print(data.isnull().sum())

data=data.dropna ()

#make string as datetime to identify individual components easily

data['START_DATE*'] = pd.to_datetime (data['START_DATE*'], format="%m/%d/%Y %H:%M") 
data['END_DATE*'] = pd.to_datetime (data['END_DATE*'], format="%m/%d/%Y %H:%M")


data['HOUR']= [x.hour for x in data['START_DATE*']]

data['DAY']= [x.day for x in data['START_DATE*']]
data['MONTH']= [x.month for x in data['START_DATE*']]

data['WEEKDAY'] = [calendar.day_name[x.dayofweek] for x in data['START_DATE*']]
data['DAY_OF_WEEK']= [x.dayofweek for x in data['START_DATE*']]

sns.countplot(x='CATEGORY*',data=data)

sns.countplot(x='PURPOSE*',data=data)

data['MILES*'].plot.hist()

hours = data['HOUR'].value_counts()

hours.plot(kind='bar', color='red', figsize=(10,5))

plt.xlabel('Hours')

plt.ylabel('Frequency')

plt.title('Number of trips Vs hours')

days = data['WEEKDAY'].value_counts()

days.plot(kind='barh', color='seagreen', figsize=(10,5))

plt.xlabel('Days')

plt.ylabel('Frequency')

plt.title('Number of trips Vs days')

months = data['MONTH'].value_counts()

months.plot(kind='barh', color= 'darkblue', figsize=(10,5))

plt.xlabel('Months')

plt.ylabel('Frequency')

plt.title('Number of trips Vs months')

months = data['DAY'][data['MONTH' ]==12].value_counts()
months.plot(kind='bar', color='darkgray', figsize=(10,5))

plt.xlabel('days of december')

plt.ylabel('Frequency')

plt.title('Number of trips Vs days of december')

months =data['STOP*'].value_counts().nlargest(10)

months.plot(kind='barh', color='lightgreen', figsize=(10,5))

plt.xlabel('Frequency')

plt.ylabel('Destination Ppoint')

plt.title('Destination point Vs Frequency')



months =data['START*'].value_counts().nlargest(10)

months.plot(kind='barh', color='lightblue', figsize=(10,5))

plt.xlabel('Frequency')

plt.ylabel('Pickup point')

plt.title('Pickup point Vs Frequency')